# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: litedb
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  timeout: 5000

# DATABASE CONFIGURATIONS
primary: &primary
  <<: *default
  database: storage/<%= Rails.env %>_rubyvideo.sqlite3

development:
  primary: *primary

test:
  primary: *primary

production:
  primary: *primary
