# name: deploy to production

# on:
#   push:
#     branches: [main]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     # container: adrienpoly/rails_hetzner_mrsk
#     env:
#       RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
#       MRSK_REGISTRY_PASSWORD: ${{ secrets.MRSK_REGISTRY_PASSWORD }}

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Ruby
#         uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: 3.2.0
#           bundler-cache: true

#       - name: Install dependencies
#         run: gem install mrsk

#       - uses: webfactory/ssh-agent@v0.7.0
#         with:
#           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#       - name: Login to DockerHub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.MRSK_REGISTRY_PASSWORD }}

#       - name: Set up QEMU test
#         uses: docker/setup-qemu-action@v2

#       - name: Pull Docker Image
#         run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/rubyvideo || true

#       - name: Set up Docker Buildx.
#         uses: docker/setup-buildx-action@v2

#       - name: Build and push
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/rubyvideo:latest
#           cache-from: type=gha # https://docs.docker.com/build/cache/backends/gha/
#           cache-to: type=gha,mode=max

#       - name: MRSK deploy
#         run: mrsk deploy --skip-push
